### ISSUE TITLE
Rewrite the Reference Generator into Java

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/docs#24]
### Summary
Python was a bad choice. Firstly i'll rewrite what I have into java to have any checkpoint. Then the generator will be somehow merged with the engine repo, enabling us to generate docs into the same directory as `std-lib`, so that you'll have in `std-lib` a directory called `docs` with all docs for std-lib, parallel to the src. Then LS and ide will be adjusted to query for a doc already generated into this directory, not having to regenerate docs every time you select something in a searcher - and also - it will have it automatically "connected" to proper AST that way. (not using pure gen anymore.)

**Comment by iamrecursion** [comment]
I disagree that this should be in Java. Given the future of the syntax handling is in Rust I would wager that this should be in Rust. Furthermore, the eventual plan is to move the language server to Rust as well, meaning that if this is written in Java it would have to be re-written again. Where does the Java requirement come from?

**Comment by iamrecursion** [comment]
Closed in favour of enso-org/enso/issues/1697.
